publish:
  whoami: asf-site
  
github:
  description: "Apache Submarine"
  homepage: https://submarine.apache.org/
  labels:
    - apache
    - submarine
    - web-site
  enabled_merge_buttons:
    squash: false
    merge: false
    rebase: false
